### PR TITLE
Add new flairs

### LINKED ISSUE #5: Rust as a flair. 👁
----------------------I think the title is self explanatory. ------------------

### LINKED ISSUE #6: TypeScript flair
some of us just like vanilla TypeScript :)

### LINKED ISSUE #7: Julia as a flair :)
Feature request for adding Julia language as a flair. Reference for the language: https://julialang.org/

### LINKED ISSUE #8: Javascript as a flair
how did you forget about javascript

### PR DESCRIPTION
**Pull request by acollierr17**
This PR includes requested flairs and resolves #5, resolves #6, resolves #7, and resolves #8. Also, I ran all the SVG files through [SVGOMG](https://jakearchibald.github.io/svgomg/) as mentioned in #21 to clean up the files overall.

*Edit:* I have slightly modified the CSS3 SVG, removing the "CSS" portion from the top of the logo. All SVG files have been directly sourced from Wikimedia.

*Edit 2:* Made some grammatical fixes.

### CODE REVIEW

**Review by RazerMoon — APPROVED** [review]
👍

**Comment by kiprasmel** [comment]
haskell pls?:>

**Comment by acollierr17** [comment]
> haskell pls?:>

Sure thing!

**Comment by bmoe24x** [comment]
***just commenting to link the PR to the issues by using a keyword***

resolves #5, resolves #6, resolves #7, resolves #8, resolves #21

**Comment by bmoe24x** [comment]
Add a keyword before your issue link such as `resolves` or `closes` then the `#` and `<issue-number>` to link this PR to the issues

**Comment by acollierr17** [comment]
> Add a keyword before your issue link such as `resolves` or `closes` then the `#` and `<issue-number>` to link this PR to the issues

All those issues have already been referenced in the commit (I've been taking advantage of that functionality for a long time now). You can see by going to one of the issues listed above and you should see two references. One related to the commit and the other related to this PR.

**Review by rezk2ll — APPROVED** [review]

**Comment by bmoe24x** [comment]
> > Add a keyword before your issue link such as `resolves` or `closes` then the `#` and `<issue-number>` to link this PR to the issues
> 
> All those issues have already been referenced in the commit (I've been taking advantage of that functionality for a long time now). You can see by going to one of the issues listed above and you should see two references. One related to the commit and the other related to this PR.

You've referenced them yes, but they are not linked. If you are on desktop, you can see on the right sidebar it will show Linked Issues as well as in the issues it will show a more complete reference if you [use a keyword](https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue). No worries though, just a suggestion.

**Comment by acollierr17** [comment]
> > > Add a keyword before your issue link such as `resolves` or `closes` then the `#` and `<issue-number>` to link this PR to the issues
> > 
> > 
> > All those issues have already been referenced in the commit (I've been taking advantage of that functionality for a long time now). You can see by going to one of the issues listed above and you should see two references. One related to the commit and the other related to this PR.
> 
> You've referenced them yes, but they are not linked. If you are on desktop, you can see on the right sidebar it will show Linked Issues as well as in the issues it will show a more complete reference if you [use a keyword](https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue). No worries though, just a suggestion.

I actually did not know it didn't show up on mobile. That makes a lot of sense now. I made the changes. Thank you for the knowledge!

**Comment by benawad** [comment]
before I can merge, we need to add it on react native side too https://github.com/benawad/vsinder-app/pull/16

**Comment by acollierr17** [comment]
> before I can merge, we need to add it on react native side too [benawad/vsinder-app#16](https://github.com/benawad/vsinder-app/pull/16)

I was actually thinking about that too. How did you go about creating the files? I saw they were JavaScript files using components. Did you generate those or manually create them?

**Comment by benawad** [comment]
https://react-svgr.com/docs/cli/

**Comment by bmoe24x** [comment]
(can we get kubernetes & kafka while we are at it?)

**Comment by acollierr17** [comment]
> (can we get kubernetes & kafka while we are at it?)

Definitely can! I'll do it tomorrow.

**Pull request merged**
