### PR TITLE
add non binary

### PR DESCRIPTION
**Pull request by HoloPollock**
add non binary gender option should be fine just would only show up in everyone for now

relevant link for app change PR: https://github.com/benawad/vsinder-app/pull/8

### CODE REVIEW

**Comment by JCDetwiler** [comment]
Related to issue #19

**Comment by benawad** [comment]
how do you want the matching algorithm to work?

**Comment by HoloPollock** [comment]
I’m current thought is just have non binary people show up only in everyone. Like i could go try to add an option to only see non binary people (but I feel like it would be better then to have them be check box’s rather than radio boxes and that’s a bigger change) for simplicity for now might aswell just have it be only in everyone

**Comment by HoloPollock** [comment]
If you think I would be better to only push with the bigger change let me know and I can look in to trying to do that ASAP

**Comment by Amanse** [comment]
@HoloPollock appreciation message because they are awesome!!

**Comment by benawad** [comment]
Ok, sounds good

**Pull request merged**
